name: Slides

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: blester125/beamer-image:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Slides
      run: |
        make clean
        make
    - uses: actions/upload-artifact@v1
      if: success()
      with:
          name: slides
          path: Your-Neural-Network-Is-Probably-Wrong.pdf
  commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete slides
      run: |
          rm -rf Your-Neural-Network-Is-Probably-Wrong.pdf
    - uses: actions/download-artifact@v1
      with:
          name: slides
          path: tmp
    - name: Move artifacts
      run: |
          mv tmp/* .
          rm -rf tmp
    - name: Commit Files
      shell: bash
      run: |
          git add -A
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Built Slides"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
